"""Initial migration.

Revision ID: 15693d89a9fd
Revises: 
Create Date: 2023-12-12 17:45:11.485790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15693d89a9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
