"""rename department

Revision ID: 406aa0f483fa
Revises: 174d42aee301
Create Date: 2023-12-12 17:52:02.386386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406aa0f483fa'
down_revision = '174d42aee301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
